name: Reusable workflow example

on:
  workflow_call:
    inputs:
      mailbot-from:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo ${{ inputs.mailbot-from }}
