name: Test running commit emailer
on: push

jobs:
  call-emailer:
    runs-on: ubuntu-latest
    env:
      MAILBOT_PASSWORD: supersecret
    steps:
      - uses: sanjit-bhat/github-mailbot@main
        with:
          host: smtp.gmail.com
          port: 587
          from: mit.pdos.mailbot@gmail.com
          to: sanjit.bhat@gmail.com
