name: Testing commit emailer
on: push

jobs:
  mailbot:
    uses: sanjit-bhat/github-mailbot/.github/workflows/mailbot.yml@main
    with:
      host: smtp.gmail.com
      port: 587
      from: mit.pdos.mailbot@gmail.com
      to: sanjit.bhat@gmail.com,sanjitb@mit.edu
    secrets:
      password: ${{ secrets.MAILBOT_PASSWORD }}
